<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<PlatformTarget>x64</PlatformTarget>
		<RuntimeIdentifier>win-x64</RuntimeIdentifier>
		<SelfContained>false</SelfContained>
		<RootNamespace>CelesteAndroid.Desktop</RootNamespace>
		<AssemblyName>CelesteDesktop</AssemblyName>
	</PropertyGroup>
	<ItemGroup>
		<ProjectReference Include="..\..\external\FNA\FNA.Core.csproj" />
		<ProjectReference Include="..\Steamworks.NET\Steamworks.NET.csproj" />
		<ProjectReference Include="..\Celeste.Patcher\Celeste.Patcher.csproj" />
		<ProjectReference Include="..\Celeste.Android.Patches\Celeste.Android.Patches.csproj"
			ReferenceOutputAssembly="false" OutputItemType="Content" CopyToOutputDirectory="PreserveNewest" />
	</ItemGroup>
	<ItemGroup>
		<None Include="$(RepoRoot)natives\win-x64\*.dll" CopyToOutputDirectory="PreserveNewest" Visible="false" />
		<None Include="$(RepoRoot)fmod\libs\win-x64\*.dll" CopyToOutputDirectory="PreserveNewest" Visible="false" />
	</ItemGroup>
</Project>
